### ISSUE TITLE
Some svg files generated by batik can not opened by this svg editor.

### ISSUE THREAD

**Issue by rubby33** [okohll/svg_editor#2]
I have used batik to generated some svg files.
But they can not opened by this svg editor.
However, these svg files can be opend by chrome and Squiggle( the SVG Browser of batik).
What's more, these svg files can be opened by GLIPSGraffiti svg editor 1.3,
but not 1.5.
# The error is:

Exception in thread "Thread-3" org.apache.batik.bridge.BridgeException: file:/C:/success.svg:-1
Cannot find the referenced element:
"file:/C:/success.svg#clipPath1"
specified on the element <rect> - may be a problem of 'id'
    at org.apache.batik.bridge.BridgeContext.getReferencedNode(Unknown Source)
    at org.apache.batik.bridge.BridgeContext.getReferencedElement(Unknown Source)
    at org.apache.batik.bridge.CSSUtilities.convertClipPath(Unknown Source)
    at org.apache.batik.bridge.AbstractGraphicsNodeBridge.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.SVGShapeElementBridge.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
    at org.apache.batik.bridge.GVTBuilder.build(Unknown Source)
    at fr.itris.glips.svgeditor.display.canvas.SVGCanvas.initializeCanvas(SVGCanvas.java:321)
    at fr.itris.glips.svgeditor.display.canvas.SVGCanvas.setURI(SVGCanvas.java:277)
    at fr.itris.glips.svgeditor.io.managers.FileOpen$1.run(FileOpen.java:140)
    at fr.itris.glips.svgeditor.io.IOManager$1.run(IOManager.java:74)

**Comment by evgenius1424** [comment]
Hi. Are you resolve it?

**Comment by okohll** [comment]
No, I'm afraid I'm not working on this product any more, someone else will have to take it over if they have enough interest

**Comment by rubby33** [comment]
no one care about this problem.
